
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manh
 */
public class Nhanvien extends javax.swing.JPanel {

    ResultSet rs, rsSearch;
    Statement st;
    Vector vec, rowTen;
    PreparedStatement ps, psSearch;
    DefaultTableModel tblModel;
    Helper.DBHelper db = new Helper.DBHelper();
    Connection con;
    SimpleDateFormat ft = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat ftError = new SimpleDateFormat("yyyy/MM/dd");
    SetImage img = new SetImage();
    Date now = new Date();

    public Nhanvien() {
        initComponents();

        tblEmp.getTableHeader().setBackground(new Color(0, 0, 0, 0));
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        btnLuu.setEnabled(false);
        tblModel = new DefaultTableModel();
        tblModel.addColumn("Tài khoản");
//        tblModel.addColumn("Mật khẩu");
        tblModel.addColumn("Họ và tên");
        tblModel.addColumn("Giới tính");
        tblModel.addColumn("Ngày sinh");
        tblModel.addColumn("Số điện thoại");
        tblModel.addColumn("Email");
        tblModel.addColumn("Địa chỉ");
        tblModel.addColumn("Hình ảnh");

        tblEmp.setModel(tblModel);
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        txtPhone = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUser1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtBirthday = new com.toedter.calendar.JDateChooser();
        txtHinh = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tarAddress = new javax.swing.JTextPane();
        lbHinh = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        btnBrowse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(850, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(128, 128, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhân Viên");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 860, 70));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Mật Khẩu  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, 40));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Giới tính");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, 40));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Số Điện Thoại  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, 40));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Họ và Tên");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 70, 40));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Tài Khoản ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 70, 40));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Email    ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 70, 40));

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEmp.setFocusable(false);
        tblEmp.setGridColor(new java.awt.Color(0, 0, 0));
        tblEmp.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblEmp.setRowHeight(25);
        tblEmp.setShowVerticalLines(false);
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmp);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 840, 200));

        txtPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPhone.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 170, 30));

        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 170, 30));

        txtUser1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtUser1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUser1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUser1.setDragEnabled(true);
        txtUser1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser1ActionPerformed(evt);
            }
        });
        txtUser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUser1KeyPressed(evt);
            }
        });
        jPanel1.add(txtUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 170, 30));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Xác Nhận mật Khẩu");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 130, 20));

        rdMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdMale);
        rdMale.setSelected(true);
        rdMale.setText("Nam");
        rdMale.setToolTipText("");
        jPanel1.add(rdMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        rdFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdFemale);
        rdFemale.setText("Nữ");
        rdFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Thêm");

        javax.swing.GroupLayout btnAddLayout = new javax.swing.GroupLayout(btnAdd);
        btnAdd.setLayout(btnAddLayout);
        btnAddLayout.setHorizontalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnAddLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnAddLayout.setVerticalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnAddLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 80, 30));

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Làm Mới");

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnResetLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel13)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnResetLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel13)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 80, 30));

        btnEdit.setBackground(new java.awt.Color(0, 0, 0));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sửa");

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnEditLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnEditLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 80, 30));

        btnLuu.setBackground(new java.awt.Color(0, 0, 0));
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Lưu");

        javax.swing.GroupLayout btnLuuLayout = new javax.swing.GroupLayout(btnLuu);
        btnLuu.setLayout(btnLuuLayout);
        btnLuuLayout.setHorizontalGroup(
            btnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnLuuLayout.setVerticalGroup(
            btnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 80, 30));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Xóa");

        javax.swing.GroupLayout btnDeleteLayout = new javax.swing.GroupLayout(btnDelete);
        btnDelete.setLayout(btnDeleteLayout);
        btnDeleteLayout.setHorizontalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        btnDeleteLayout.setVerticalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, 30));

        jLabel17.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Địa chỉ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 60, 40));

        jLabel18.setBackground(new java.awt.Color(153, 153, 153));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Ngày sinh");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, 40));

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 170, 30));

        txtBirthday.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(txtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 170, -1));

        txtHinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        tarAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tarAddress.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tarAddress);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 190, 120));

        lbHinh.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lbHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 200));

        txtPass1.setActionCommand("<Not Set>");
        txtPass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtPass1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPass1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 170, -1));

        txtPass.setActionCommand("<Not Set>");
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtPass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPass.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 170, -1));

        btnBrowse.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chọn ảnh");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnBrowseLayout = new javax.swing.GroupLayout(btnBrowse);
        btnBrowse.setLayout(btnBrowseLayout);
        btnBrowseLayout.setHorizontalGroup(
            btnBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnBrowseLayout.setVerticalGroup(
            btnBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void rdFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFemaleActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        // TODO add your handling code here:
        btnDelete.setEnabled(true);
        btnEdit.setEnabled(true);
        btnLuu.setEnabled(false);
        txtUser1.setEnabled(false);
        txtPass.setEnabled(false);
        txtPass1.setEnabled(false);
        txtEmail.setEnabled(false);
        tarAddress.setEnabled(false);
        txtName.setEnabled(false);
        txtPhone.setEnabled(false);
        txtBirthday.setEnabled(false);
        txtHinh.setEnabled(false);
        rdFemale.setEnabled(false);
      rdMale.setEnabled(false);
        btnBrowse.setEnabled(false);
        int line = tblEmp.getSelectedRow();
        try {
            String sql = "select Password from Employee where UsernameEmp=?";
            ps = con.prepareStatement(sql);
            ps.setString(1, (String) tblModel.getValueAt(line, 0));
            rs = ps.executeQuery();
            if (rs.next()) {
                txtPass.setText(rs.getString(1));
                txtPass1.setText(rs.getString(1));
            }
            String username = (String) tblModel.getValueAt(line, 0);
            String name = (String) tblModel.getValueAt(line, 1);
            String sex = (String) tblModel.getValueAt(line, 2);
            Date birthday = ft.parse((String) tblModel.getValueAt(line, 3));
            String phone = (String) tblModel.getValueAt(line, 4);
            String email = (String) tblModel.getValueAt(line, 5);
            String address = (String) tblModel.getValueAt(line, 6);
            String image = (String) tblModel.getValueAt(line, 7);
           
            
            txtUser1.setText(username);
            txtName.setText(name);
            txtBirthday.setDate(birthday);
            txtPhone.setText(phone);
            txtEmail.setText(email);
            tarAddress.setText(address);
            lbHinh.setText(image);
           txtHinh.setText(image);
            
            img.setImageLabel(lbHinh, "image//" + image);
            if (sex.equals("Nam")) {
                rdMale.setSelected(true);
            } else {
                rdFemale.setSelected(true);
            }
        } catch (ParseException e) {
        } catch (SQLException ex) {
            Logger.getLogger(Nhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblEmpMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm nhân viên mới  ?");
        while (true) {
            try {
                ps = con.prepareStatement("select * from Employee where UsernameEmp = ?");
                ps.setString(1, txtUser1.getText().trim());
                rs = ps.executeQuery();
                if (txtUser1.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(this, "Tài khoản không được để trống !");
                    txtUser1.grabFocus();
                    return;
                } else if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Tài khoản này đã tồn tại !");
                    txtUser1.grabFocus();
                    return;
                } else if (txtUser1.getText().trim().length() > 30) {
                    JOptionPane.showMessageDialog(this, "Tài khoản không được lớn hơn 30 kí tự ! ");
                    txtUser1.grabFocus();
                    return;
                } else if (txtUser1.getText().trim().length() < 6) {
                    JOptionPane.showMessageDialog(this, "Tài khoản phải lớn hơn 6 kí tự  ! ");
                    txtUser1.grabFocus();
                    return;
                } else if (!txtUser1.getText().trim().matches("[A-Za-z0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Tài khoản phải có chữ và số ! ");
                    txtUser1.grabFocus();
                    return;
                } else {
                    break;
                }
            } catch (Exception e) {
            }

        }
        while (true) {

            if (txtPass.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() > 18) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được lớn hơn 18 kí tự ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() < 6) {
                JOptionPane.showMessageDialog(this, "Mật khẩu phải lớn hơn 6 kí tự  ! ");
                txtPass.grabFocus();
                return;
            } else if (!txtPass.getText().matches("[A-Za-z0-9]+")) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được có khoảng cách và kí tự đặc biệt ! ");
                txtPass.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtPass1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không được để trống !");
                txtPass1.grabFocus();
                return;
            } else if (!txtPass1.getText().trim().equals(txtPass.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu phải giống mật khẩu !");
                txtPass1.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Họ và tên không được để trống !");
                txtName.grabFocus();
                return;
            } else if (txtName.getText().trim().length() > 30) {
                JOptionPane.showMessageDialog(this, "Tên không được lớn hơn 30 kí tự ! ");
                txtName.grabFocus();
                return;
            }
            {
                break;
            }

        }
//        while (true) {
//            if (ftError.format(txtBirthday.getDate()).compareTo("2002/01/01") >= 0) {
//                JOptionPane.showMessageDialog(this, "Nhân viên phải đủ 18 tuổi !");
//                txtBirthday.grabFocus();
//                return;
//            } else {
//                break;
//            }
//
//        }
//        if (!txtPhone.getText().trim().equals("")) {
//            while (true) {
//                 if (!txtPhone.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
//                    JOptionPane.showMessageDialog(this, "Không đúng định dạng số điện thoại ! Ví dụ : 012345678x hoặc 098765432x");
//                    txtPhone.grabFocus();
//                    return;
//                } else {
//                    break;
//                }
//
//            }
//        }
        if (!txtEmail.getText().trim().equals("")) {
            while (true) {
                if (!txtEmail.getText().trim().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")) {
                    JOptionPane.showMessageDialog(this, "Không đúng định dạng Email ! Ví dụ : (abcdef@gmail.com) ");
                    txtEmail.grabFocus();
                    return;
                } else {
                    break;
                }
            }
        }
        while (true) {
            if (tarAddress.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống !");
                tarAddress.grabFocus();
                return;
            } else if (tarAddress.getText().trim().length() > 100) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được lớn hơn 100 kí tự ! ");
                tarAddress.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtHinh.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Hình ảnh không được để trống !");
                txtHinh.grabFocus();
                return;
            } else {
                break;
            }

        }

        try {
            ps = con.prepareStatement("Insert into Employee values(?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txtUser1.getText());
            ps.setString(2, txtPass.getText());
            ps.setString(3, txtName.getText());
            if (rdMale.isSelected()) {
                ps.setString(4, "Nam");
            } else {
                ps.setString(4, "Nữ");
            }
            ps.setString(5, ft.format(txtBirthday.getDate()));
            ps.setString(6, txtPhone.getText());
            ps.setString(7, txtEmail.getText());
            ps.setString(8, tarAddress.getText());
            ps.setString(9, txtHinh.getText());

            ps.executeUpdate();
            tblModel.getDataVector().removeAllElements();
            loadData();

            JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công ! ");
        } catch (SQLException ex) {
            Logger.getLogger(Nhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        txtUser1.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtPass.setText("");
        txtPass1.setText("");
        txtPhone.setText("");
        tarAddress.setText("");
        img.setImageLabel(lbHinh, "image//trongsuot.png");
        txtHinh.setText("");
        rdMale.setSelected(true);
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        btnAdd.setEnabled(true);
        btnLuu.setEnabled(false);
        txtUser1.setEnabled(true);
        tblModel.getDataVector().removeAllElements();
        txtPass.setEnabled(true);
        txtPass1.setEnabled(true);
        txtEmail.setEnabled(true);
        tarAddress.setEnabled(true);
        txtName.setEnabled(true);
        txtPhone.setEnabled(true);
        txtBirthday.setEnabled(true);
        txtHinh.setEnabled(true);
        rdFemale.setEnabled(true);
        rdMale.setEnabled(true);
        btnBrowse.setEnabled(true);

        loadData();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        txtUser1.setEnabled(false);
        btnDelete.setEnabled(true);
        btnEdit.setEnabled(true);
        btnAdd.setEnabled(false);
        btnLuu.setEnabled(true);
        btnBrowse.setEnabled(true);
        txtPass.setEnabled(true);
        txtPass1.setEnabled(true);
        txtEmail.setEnabled(true);
        tarAddress.setEnabled(true);
        txtName.setEnabled(true);
        txtPhone.setEnabled(true);
        txtBirthday.setEnabled(true);
        txtHinh.setEnabled(true);
        rdFemale.setEnabled(true);
        rdMale.setEnabled(true);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn lưu ?");
        while (true) {
            if (txtPass.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() > 18) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được lớn hơn 18 kí tự ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() < 6) {
                JOptionPane.showMessageDialog(this, "Mật khẩu phải lớn hơn 6 kí tự  ! ");
                txtPass.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtPass1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không được để trống !");
                txtPass1.grabFocus();
                return;
            } else if (!txtPass1.getText().trim().equals(txtPass.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu phải giống mật khẩu !");
                txtPass1.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Họ và tên không được để trống !");
                txtName.grabFocus();
                return;
            } else if (txtName.getText().trim().length() > 30) {
                JOptionPane.showMessageDialog(this, "Họ và tên không được lớn hơn 30 kí tự ! ");
                txtName.grabFocus();
                return;
            }
            {
                break;
            }

        }
       
//        if (!txtPhone.getText().trim().equals("")) {
//            while (true) {
//                 if (!txtPhone.getText().trim().matches("0[1-9]{1}\\d{7,8}")) {
//                    JOptionPane.showMessageDialog(this, "Không đúng định dạng số điện thoại ! Ví dụ : 012345678x hoặc 098765432x");
//                    txtPhone.grabFocus();
//                    return;
//                } else {
//                    break;
//                }
//
//            }
//        }
        if (!txtEmail.getText().trim().equals("")) {
            while (true) {
                if (!txtEmail.getText().trim().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")) {
                    JOptionPane.showMessageDialog(this, "Không đúng định dạng Email ! Ví dụ : (abcdef@gmail.com) ");
                    txtEmail.grabFocus();
                    return;
                } else {
                    break;
                }
            }
        }
        while (true) {
            if (tarAddress.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống !");
                tarAddress.grabFocus();
                return;
            } else if (tarAddress.getText().trim().length() > 100) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được lớn hơn 100 kí tự ! ");
                tarAddress.grabFocus();
                return;
            }
            {
                break;
            }

        }
        while (true) {
            if (txtHinh.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Hình ảnh không được để trống !");
                txtHinh.grabFocus();
                return;
            } else {
                break;
            }
        }

        try {
            ps = con.prepareStatement("update Employee set Password=?,NameEmp=?,Gender=?,Birthday=?,Phone=?,Email=?,Address=?,Hinh=? where UsernameEmp=?");

            ps.setString(9, txtUser1.getText());
            ps.setString(1, txtPass.getText());
            ps.setString(2, txtName.getText());
            ps.setString(4, ft.format(txtBirthday.getDate()));
            ps.setString(5, txtPhone.getText());
            ps.setString(6, txtEmail.getText());
            ps.setString(7, tarAddress.getText());
            ps.setString(8, txtHinh.getText());
            if (rdMale.isSelected()) {
                ps.setString(3, "Nam");
            } else {
                ps.setString(3, "Nữ");
            }

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Lưu thành công ! ");
            tblModel.getDataVector().removeAllElements();
            loadData();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa ?");
        if (click == 0) {
            try {
                ps = con.prepareStatement("select * from [Order] where UsernameEmp=?");
                ps.setString(1, txtUser1.getText());
                rs = ps.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Nhân viên đang còn đơn hàng, không thể xóa.");
                } else {
                    try {
                        ps = con.prepareStatement("Delete from Employee where UsernameEmp=?");
                        ps.setString(1, txtUser1.getText());
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Xóa thành công ! ");

                        tblModel.getDataVector().removeAllElements();
                        loadData();
                    } catch (Exception e) {
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Nhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtUser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUser1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser1KeyPressed

    private void txtUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser1ActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
          JFileChooser fileChooser = new JFileChooser("image");
        FileFilter filter = new FileNameExtensionFilter("Image file", "gjf", "jpg", "png");

        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false);

        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            while (true) {
                if (!fileChooser.getSelectedFile().getName().matches("([^\\s]+(\\.(?i)(jpg|png|gif|bmp))$)")) {
                    JOptionPane.showMessageDialog(null, "Định dạng file hình đuôi phải là GIF, JPG, PNG !");
                    return;
                } else {
                    break;
                }
            }
            String imgFile = fileChooser.getSelectedFile().getName();
            txtHinh.setText(imgFile);
            img.setImageLabel(lbHinh, "image//" + imgFile);
        }
    }//GEN-LAST:event_jLabel1MousePressed
    NumberFormat nft = new DecimalFormat("#,###");

    private void loadData() {
        con = db.getCon();
        try {
            ps = con.prepareStatement("Select * from Employee");
            rs = ps.executeQuery();
            while (rs.next()) {
                vec = new Vector();
                vec.add(rs.getString(1));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
                vec.add(rs.getString(6));
                vec.add(rs.getString(7));
                vec.add(rs.getString(8));
                vec.add(rs.getString(9));

                tblModel.addRow(vec);
            }
            tblEmp.setModel(tblModel);
        } catch (SQLException ex) {

            Logger.getLogger(Nhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnBrowse;
    private javax.swing.JPanel btnDelete;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnLuu;
    private javax.swing.JPanel btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbHinh;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextPane tarAddress;
    private javax.swing.JTable tblEmp;
    private com.toedter.calendar.JDateChooser txtBirthday;
    public static javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHinh;
    public static javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    public static javax.swing.JTextField txtPhone;
    public static javax.swing.JTextField txtUser1;
    // End of variables declaration//GEN-END:variables
}
